package com.onlineimoti.calllog

data class CrmContactNormalizedFields(
    val originalPhone: String,
    val displayName: String,
    val additionalPhone: String,
    val organization: String,
    val jobTitle: String,
    val website: String,
    val note: String,
    val groupName: String,
    val customText: String,
    val namePrefix: String,
    val givenName: String,
    val middleName: String,
    val familyName: String,
    val nameSuffix: String,
    val phoneticName: String,
    val phoneHome: String,
    val phoneWork: String,
    val phoneOther: String,
    val phoneFaxWork: String,
    val phoneFaxHome: String,
    val phonePager: String,
    val emailHome: String,
    val emailWork: String,
    val emailOther: String,
    val department: String,
    val officeLocation: String,
    val websiteHome: String,
    val websiteBlog: String,
    val websiteProfile: String,
    val addressHomeStreet: String,
    val addressHomeCity: String,
    val addressHomeRegion: String,
    val addressHomePostcode: String,
    val addressHomeCountry: String,
    val addressWorkStreet: String,
    val addressWorkCity: String,
    val addressWorkRegion: String,
    val addressWorkPostcode: String,
    val addressWorkCountry: String,
    val birthday: String,
    val anniversary: String,
    val otherDate: String,
    val nickname: String,
    val sipAddress: String,
    val im: String,
    val relationSpouse: String,
    val relationAssistant: String,
    val relationManager: String,
    val relationReferredBy: String,
) {
    companion object {
        fun from(
            fields: CallReportStableCrmContactWriter.Fields,
            originalPhone: String,
            @Suppress("UNUSED_PARAMETER") existingRawContactId: Long,
        ): CrmContactNormalizedFields {
            return CrmContactNormalizedFields(
                originalPhone = originalPhone,
                displayName = fields.displayName.trim().ifBlank { originalPhone },
                additionalPhone = PhoneNormalizer.normalize(fields.additionalPhone).takeIf { it.isNotBlank() && it != originalPhone }.orEmpty(),
                organization = fields.organization.trim(),
                jobTitle = fields.jobTitle.trim(),
                website = fields.website.trim(),
                note = fields.note.trim(),
                groupName = fields.groupName.trim(),
                customText = fields.customText.trim(),
                namePrefix = fields.namePrefix.trim(),
                givenName = fields.givenName.trim(),
                middleName = fields.middleName.trim(),
                familyName = fields.familyName.trim(),
                nameSuffix = fields.nameSuffix.trim(),
                phoneticName = fields.phoneticName.trim(),
                phoneHome = PhoneNormalizer.normalize(fields.phoneHome),
                phoneWork = PhoneNormalizer.normalize(fields.phoneWork),
                phoneOther = PhoneNormalizer.normalize(fields.phoneOther),
                phoneFaxWork = PhoneNormalizer.normalize(fields.phoneFaxWork),
                phoneFaxHome = PhoneNormalizer.normalize(fields.phoneFaxHome),
                phonePager = PhoneNormalizer.normalize(fields.phonePager),
                emailHome = fields.emailHome.trim(),
                emailWork = fields.emailWork.trim(),
                emailOther = fields.emailOther.trim(),
                department = fields.department.trim(),
                officeLocation = fields.officeLocation.trim(),
                websiteHome = fields.websiteHome.trim(),
                websiteBlog = fields.websiteBlog.trim(),
                websiteProfile = fields.websiteProfile.trim(),
                addressHomeStreet = fields.addressHomeStreet.trim(),
                addressHomeCity = fields.addressHomeCity.trim(),
                addressHomeRegion = fields.addressHomeRegion.trim(),
                addressHomePostcode = fields.addressHomePostcode.trim(),
                addressHomeCountry = fields.addressHomeCountry.trim(),
                addressWorkStreet = fields.addressWorkStreet.trim(),
                addressWorkCity = fields.addressWorkCity.trim(),
                addressWorkRegion = fields.addressWorkRegion.trim(),
                addressWorkPostcode = fields.addressWorkPostcode.trim(),
                addressWorkCountry = fields.addressWorkCountry.trim(),
                birthday = fields.birthday.trim(),
                anniversary = fields.anniversary.trim(),
                otherDate = fields.otherDate.trim(),
                nickname = fields.nickname.trim(),
                sipAddress = fields.sipAddress.trim(),
                im = fields.im.trim(),
                relationSpouse = fields.relationSpouse.trim(),
                relationAssistant = fields.relationAssistant.trim(),
                relationManager = fields.relationManager.trim(),
                relationReferredBy = fields.relationReferredBy.trim(),
            )
        }
    }
}
